import simon from "@/assets/images/call_to_action/creator-1.webp";
import chief from "@/assets/images/call_to_action/creator-2.webp";
import morten from "@/assets/images/call_to_action/creator-3.webp";
import kammas from "@/assets/images/call_to_action/creator-4.webp";
import { CreatorProfile } from "../sortOptions";

const baseTime = Date.now();

export const creators: CreatorProfile[] = [
  {
    id: "1",
    name: "Simon Talbot",
    category: "Comedy",
    uploads: 10,
    image: simon,
    createdAt: baseTime - 1000 * 60 * 60 * 1,
  },
  {
    id: "2",
    name: "Chief1",
    category: "Music",
    uploads: 20,
    image: chief,
    createdAt: baseTime - 1000 * 60 * 60 * 2,
  },
  {
    id: "3",
    name: "Morten Bonde",
    category: "Publication",
    uploads: 15,
    image: morten,
    createdAt: baseTime - 1000 * 60 * 60 * 3,
  },
  {
    id: "4",
    name: "Kammas kantine",
    category: "Cooking",
    uploads: 40,
    image: kammas,
    createdAt: baseTime - 1000 * 60 * 60 * 4,
  },
  {
    id: "5",
    name: "Simon Talbot",
    category: "Comedy",
    uploads: 23,
    image: simon,
    createdAt: baseTime - 1000 * 60 * 60 * 5,
  },
  {
    id: "6",
    name: "Chief1",
    category: "Music",
    uploads: 56,
    image: chief,
    createdAt: baseTime - 1000 * 60 * 60 * 6,
  },
  {
    id: "7",
    name: "Morten Bonde",
    category: "Publication",
    uploads: 41,
    image: morten,
    createdAt: baseTime - 1000 * 60 * 60 * 7,
  },
  {
    id: "8",
    name: "Kammas kantine",
    category: "Cooking",
    uploads: 13,
    image: kammas,
    createdAt: baseTime - 1000 * 60 * 60 * 8,
  },
  {
    id: "9",
    name: "Simon Talbot",
    category: "Comedy",
    uploads: 12,
    image: simon,
    createdAt: baseTime - 1000 * 60 * 60 * 9,
  },
  {
    id: "10",
    name: "Chief1",
    category: "Music",
    uploads: 78,
    image: chief,
    createdAt: baseTime - 1000 * 60 * 60 * 10,
  },
  {
    id: "11",
    name: "Morten Bonde",
    category: "Publication",
    uploads: 21,
    image: morten,
    createdAt: baseTime - 1000 * 60 * 60 * 11,
  },
  {
    id: "12",
    name: "Kammas kantine",
    category: "Cooking",
    uploads: 40,
    image: kammas,
    createdAt: baseTime - 1000 * 60 * 60 * 12,
  },
  {
    id: "13",
    name: "Simon Talbot",
    category: "Comedy",
    uploads: 67,
    image: simon,
    createdAt: baseTime - 1000 * 60 * 60 * 13,
  },
  {
    id: "14",
    name: "Chief1",
    category: "Music",
    uploads: 43,
    image: chief,
    createdAt: baseTime - 1000 * 60 * 60 * 14,
  },
  {
    id: "15",
    name: "Morten Bonde",
    category: "Publication",
    uploads: 27,
    image: morten,
    createdAt: baseTime - 1000 * 60 * 60 * 15,
  },
  {
    id: "16",
    name: "Kammas kantine",
    category: "Cooking",
    uploads: 89,
    image: kammas,
    createdAt: baseTime - 1000 * 60 * 60 * 16,
  },
  {
    id: "17",
    name: "Simon Talbot",
    category: "Comedy",
    uploads: 75,
    image: simon,
    createdAt: baseTime - 1000 * 60 * 60 * 17,
  },
  {
    id: "18",
    name: "Chief1",
    category: "Music",
    uploads: 83,
    image: chief,
    createdAt: baseTime - 1000 * 60 * 60 * 18,
  },
  {
    id: "19",
    name: "Morten Bonde",
    category: "Publication",
    uploads: 37,
    image: morten,
    createdAt: baseTime - 1000 * 60 * 60 * 19,
  },
  {
    id: "20",
    name: "Kammas kantine",
    category: "Cooking",
    uploads: 93,
    image: kammas,
    createdAt: baseTime - 1000 * 60 * 60 * 20,
  },
  {
    id: "21",
    name: "Simon Talbot",
    category: "Comedy",
    uploads: 37,
    image: simon,
    createdAt: baseTime - 1000 * 60 * 60 * 21,
  },
  {
    id: "22",
    name: "Chief1",
    category: "Music",
    uploads: 28,
    image: chief,
    createdAt: baseTime - 1000 * 60 * 60 * 22,
  },
  {
    id: "23",
    name: "Morten Bonde",
    category: "Publication",
    uploads: 83,
    image: morten,
    createdAt: baseTime - 1000 * 60 * 60 * 23,
  },
  {
    id: "24",
    name: "Kammas kantine",
    category: "Cooking",
    uploads: 27,
    image: kammas,
    createdAt: baseTime - 1000 * 60 * 60 * 24,
  },
];
