export const API = {
  auth: {
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    login: "/auth/login",
    forgetPassword: "/auth/forget-password",
    resetPassword: "/auth/reset-password",
    creatorRequest: "/auth/creator-request",
    creatorSetup: "/auth/creator/setup",
    signup: "/auth/signup",
    userProfile: "/auth/user/profile",
    changePassword: "/auth/user/password",
    creatorProfile: "/auth/creator/profile",
  },
  coupon: {
    create: "/coupons/create",
    getAll: "/coupons",
    update: (id: string) => `/coupons/${id}`,
    delete: (id: string) => `/coupons/${id}`,
  },
  media: {
    videoInit: "/media/videos/init",
    videoPartUrl: "/media/videos/part-url",
    videoComplete: "/media/videos/complete",
    videoStream: "/media/videos/stream",
    fileUploadUrl: "/media/file/upload-url",
    fileConfirm: "/media/file/confirm",
    fileSignedUrl: "/media/file/signed-url",
    imagesUpload: "/media/images/upload",
  },
  content: {
    create: "/content/create",
    all: "/content/all",
    categories: "/content/categories",
    types: "/content/types",
    collection: (id: string) => `/content/collection/${id}`,
    get: (id: string) => `/content/${id}`,
    view: (id: string, userId: string) => `/content/${id}/${userId}`,
    relatedCollection: (id: string) => `/content/${id}/related-collection`,
    update: (id: string) => `/content/update/${id}`,
    delete: (id: string) => `/content/delete/${id}`,
    appearance: "/content/appearance",
    setting: "/content/setting",
  },
  collection: {
    getAll: "/collection",
    create: "/collection/create",
    update: (id: string) => `/collection/${id}`,
    delete: (id: string) => `/collection/${id}`,
  },
  creators: {
    list: "/creators",
    byId: (id: string) => `/creators/${id}`,
  },
  feed: {
    explore: "/feed/explore",
    trending: "/feed/trending",
    recent: "/feed/recent",
  },
  creatorUsers: {
    registrations: "/creator-users/registrations",
    sales: "/creator-users/sales",
    deleteRegistration: (id: string) => `/creator-users/registrations/${id}`,
  },
  creatorOverview: {
    contentPerformance: "/creator-overview/content-performance",
  },
} as const;
