"use client";

import { useTranslation } from "react-i18next";
import FormattedBody from "../Shared/FormattedBody";
import LegalContactSection from "../Shared/LegalContactSection";
import {
  Body,
  Description,
  FormattedDescription,
  Header,
  Intro,
  IntroArea,
  Meta,
  Section,
  SectionTitle,
  Title,
  Wrap,
} from "../Shared/legalPageStyles";

export default function TermsOfServiceSection() {
  const { t } = useTranslation();

  return (
    <Wrap>
      <Header>
        <Title>{t("footer.termsOfService")}</Title>
        <Meta>{t("legalPages.termsOfService.updatedAt")}</Meta>
      </Header>
      <IntroArea>
        <Intro>{t("legalPages.termsOfService.intro")}</Intro>
      </IntroArea>
      <Body>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.acceptance.title")}
          </SectionTitle>
          <Description>
            {t("legalPages.termsOfService.sections.acceptance.body")}
          </Description>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.intellectualProperty.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t(
                "legalPages.termsOfService.sections.intellectualProperty.body",
              )}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.thirdParty.title")}
          </SectionTitle>
          <Description>
            {t("legalPages.termsOfService.sections.thirdParty.body")}
          </Description>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.offensiveContent.title")}
          </SectionTitle>
          <Description>
            {t("legalPages.termsOfService.sections.offensiveContent.body")}
          </Description>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.digitalPurchase.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t(
                "legalPages.termsOfService.sections.digitalPurchase.body",
              )}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.payments.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.payments.body")}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.platform.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.platform.body")}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.liability.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.liability.body")}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.governingLaw.title")}
          </SectionTitle>
          <Description>
            {t("legalPages.termsOfService.sections.governingLaw.body")}
          </Description>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.publisherAccount.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t(
                "legalPages.termsOfService.sections.publisherAccount.body",
              )}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.publisherContent.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t(
                "legalPages.termsOfService.sections.publisherContent.body",
              )}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.useOfService.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.useOfService.body")}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.publisherRole.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.publisherRole.body")}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.publisherFees.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.publisherFees.body")}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.publisherMarketing.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t(
                "legalPages.termsOfService.sections.publisherMarketing.body",
              )}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.publisherTermination.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t(
                "legalPages.termsOfService.sections.publisherTermination.body",
              )}
            />
          </FormattedDescription>
        </Section>
        <Section>
          <SectionTitle>
            {t("legalPages.termsOfService.sections.amendments.title")}
          </SectionTitle>
          <FormattedDescription>
            <FormattedBody
              text={t("legalPages.termsOfService.sections.amendments.body")}
            />
          </FormattedDescription>
        </Section>
        <LegalContactSection translationPrefix="legalPages.termsOfService.sections.contact" />
      </Body>
    </Wrap>
  );
}
